services:
  mc_postgres:
    image: postgres:14.8-alpine3.17
    platform: "linux/amd64"
    container_name: postgres_mc
    restart: unless-stopped
    networks:
      - mynet
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=mysticcase
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=mysticcase_dev
    volumes: 
      - db:/var/lib/postgresql/data

  web:
    image: nginx:1.25-alpine3.17
    container_name: web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      # target: dev-envs
    # depends_on:
    #   - backend
    environment:
      - NGINX_PORT=80
      - MYSTIC_CASE_DOMAIN=mysticcase.io
      - MYSTIC_CASE_BACKEND_PORT=8085
    networks:
      - mynet
    ports:
      - 80:80
    volumes:
      - ./conf/nginx:/etc/nginx/templates
      - ./assets/public:/media/mystic-case/public


  backend:
    image: golang:1.20.6-alpine3.7
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      target: builder
    environment:
      - MYSTIC_CASE_DOMAIN=0.0.0.0
    networks:
      - mynet
    expose:
      - 8085
    # ports:
    #   - 8085:8085

networks:
  mynet:
    driver: bridge
    ipam:
      driver: default

volumes:
  db:
    driver: local