services:
  mc_postgres:
    image: postgres:14.8-alpine3.17
    platform: "linux/amd64"
    container_name: postgres_mc
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=mysticcase
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=mysticcase_dev
    volumes: 
      - db:/var/lib/postgresql/data

  web:
    image: nginx:1.25-alpine3.17
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      # target: dev-envs
    # depends_on:
    #   - backend
    environment:
      - NGINX_PORT=80
      - MYSTIC_CASE_DOMAIN=mysticcase.io
      - MYSTIC_CASE_BACKEND_PORT=8085
    ports:
      - 80:80
    volumes:
      - ./conf/nginx:/etc/nginx/templates
      - ./assets/public:/media/mystic-case/public


  # backend:
  #   build:
  #     context: backend
  #     target: builder

volumes:
  db:
    driver: local